### ISSUE TITLE
Error at initialize

### ISSUE THREAD

**Issue by htn274** [fitoprincipe/ipygee#3]
I have been using Python3 on Jupyter Notebook.
I had installed ipgeee, then I import it.
Finally I got the error as image below. Could you tell me why? :< Thank you!
![image](https://user-images.githubusercontent.com/26211514/62760994-98f8dc00-baaf-11e9-9674-559ec7a46fbb.png)

**Comment by fitoprincipe** [comment]
Hi @htn274, thanks for reporting!

It tries to create an `AssetManager` which needs you to have initialized your assets. For only one time, go to the Code Editor (https://code.earthengine.google.com/) to the Assets Tab and create a user space.

By the way, before importing and using `ipygee` you need to initialize Earth Engine:

``` python
import ee
ee.Initialize()
from ipygee import *
m = Map()  # I wouldn't use `map` since it is a built-in function
m.show()
```

**Comment by htn274** [comment]
> Hi @htn274, thanks for reporting!
> 
> It tries to create an `AssetManager` which needs you to have initialized your assets. For only one time, go to the Code Editor (https://code.earthengine.google.com/) to the Assets Tab and create a user space.
> 
> By the way, before importing and using `ipygee` you need to initialize Earth Engine:
> 
> ```python
> import ee
> ee.Initialize()
> from ipygee import *
> m = Map()  # I wouldn't use `map` since it is a built-in function
> m.show()
> ```

Thank you for your answer! I solved it!
